import { flavors } from "@catppuccin/palette"
import { writeFileSync } from "node:fs"
import { resolve } from "node:path"

const flavorNames = ["latte", "frappe", "macchiato", "mocha"] as const

const mapping: Record<string, string> = {
  background: "base",
  foreground: "text",
  card: "surface0",
  "card-foreground": "text",
  popover: "surface0",
  "popover-foreground": "text",
  primary: "mauve",
  "primary-foreground": "base",
  secondary: "surface1",
  "secondary-foreground": "text",
  muted: "mantle",
  "muted-foreground": "subtext1",
  accent: "surface1",
  "accent-foreground": "text",
  destructive: "red",
  border: "surface1",
  input: "surface0",
  ring: "mauve",
  "chart-1": "green",
  "chart-2": "yellow",
  "chart-3": "peach",
  "chart-4": "blue",
  "chart-5": "pink",
  sidebar: "mantle",
  "sidebar-foreground": "text",
  "sidebar-primary": "mauve",
  "sidebar-primary-foreground": "base",
  "sidebar-accent": "surface1",
  "sidebar-accent-foreground": "text",
  "sidebar-border": "surface1",
  "sidebar-ring": "mauve",
}

const lines: string[] = ["/* Auto-generated by scripts/sync-catppuccin.ts. Do not edit manually. */"]

for (const name of flavorNames) {
  const flavor = flavors[name]
  const selector =
    name === "latte"
      ? ':root, html[data-site-theme="latte"]'
      : `html[data-site-theme="${name}"]`

  lines.push("")
  lines.push(`${selector} {`)
  for (const [variable, colorKey] of Object.entries(mapping)) {
    const color = (flavor.colors as Record<string, { hex: string }>)[colorKey]
    lines.push(`  --${variable}: ${color.hex};`)
  }
  lines.push('  --radius: 0.45rem;')
  lines.push('}')
}

const outPath = resolve(import.meta.dirname, "../../..", "packages/ui/src/styles/catppuccin.css")
writeFileSync(outPath, lines.join("\n") + "\n")
console.log(`Wrote ${outPath}`)
