import { flavors } from "@catppuccin/palette"
import { writeFileSync } from "node:fs"
import { resolve } from "node:path"

const STYLES_DIR = resolve(import.meta.dirname, "../styles")

function write(filename: string, lines: string[]) {
  const outPath = resolve(STYLES_DIR, filename)
  writeFileSync(outPath, lines.join("\n") + "\n")
  console.log(`Wrote ${outPath}`)
}

function block(
  selector: string,
  vars: Record<string, string>,
  radius = "0.45rem",
): string[] {
  const lines: string[] = [`${selector} {`]
  for (const [k, v] of Object.entries(vars)) {
    lines.push(`  --${k}: ${v};`)
  }
  lines.push(`  --radius: ${radius};`)
  lines.push("}")
  return lines
}

// ---------------------------------------------------------------------------
// 1. Catppuccin
// ---------------------------------------------------------------------------
const catppuccinMapping: Record<string, string> = {
  background: "base",
  foreground: "text",
  card: "crust",
  "card-foreground": "text",
  popover: "crust",
  "popover-foreground": "text",
  primary: "mauve",
  "primary-foreground": "base",
  secondary: "surface1",
  "secondary-foreground": "text",
  muted: "mantle",
  "muted-foreground": "subtext0",
  accent: "surface1",
  "accent-foreground": "text",
  destructive: "red",
  border: "surface2",
  input: "crust",
  ring: "pink",
  "chart-1": "green",
  "chart-2": "yellow",
  "chart-3": "peach",
  "chart-4": "blue",
  "chart-5": "pink",
  sidebar: "mantle",
  "sidebar-foreground": "text",
  "sidebar-primary": "mauve",
  "sidebar-primary-foreground": "base",
  "sidebar-accent": "surface1",
  "sidebar-accent-foreground": "text",
  "sidebar-border": "surface2",
  "sidebar-ring": "mauve",
  link: "sapphire",
  "hero-gradient-start": "base",
  "hero-gradient-end": "mantle",
  "badge-primary": "mauve",
  "tag-hover": "mauve",
  "accent-1": "mauve",
  "accent-2": "blue",
  "accent-3": "green",
  "surface-raised": "crust",
  "card-border-accent": "pink",
}

const catppuccinHighlight: Record<string, string> = {
  latte: "red",
  frappe: "red",
  macchiato: "red",
  mocha: "pink",
}

;(function generateCatppuccin() {
  const flavorNames = ["latte", "frappe", "macchiato", "mocha"] as const
  const lines: string[] = ["/* Auto-generated by scripts/sync-themes.ts. Do not edit manually. */"]
  for (const name of flavorNames) {
    const flavor = flavors[name]
    const selector =
      name === "latte"
        ? ':root, html[data-site-theme="latte"]'
        : `html[data-site-theme="${name}"]`
    const vars: Record<string, string> = {}
    for (const [variable, colorKey] of Object.entries(catppuccinMapping)) {
      const color = (flavor.colors as Record<string, { hex: string }>)[colorKey]
      vars[variable] = color.hex
    }
    const hlKey = catppuccinHighlight[name]
    vars["highlight"] = (flavor.colors as Record<string, { hex: string }>)[hlKey].hex
    lines.push("", ...block(selector, vars))
  }
  write("catppuccin.css", lines)
})()

// ---------------------------------------------------------------------------
// 2. Gruvbox
// ---------------------------------------------------------------------------
const gruvbox = {
  dark: {
    bg:    "#282828", bg1:   "#3c3836", bg2:   "#504945",
    bg3:   "#665c54", bg4:   "#7c6f64",
    fg:    "#ebdbb2", fg1:   "#d5c4a1",
    red:   "#cc241d", redB:  "#fb4934",
    green: "#98971a", greenB:"#b8bb26",
    yellow:"#d79921", yellowB:"#fabd2f",
    blue:  "#458588", blueB: "#83a598",
    purple:"#b16286", purpleB:"#d3869b",
    aqua:  "#689d6a", aquaB: "#8ec07c",
    orange:"#d65d0e", orangeB:"#fe8019",
    gray:  "#928374",
  },
  light: {
    bg:    "#fbf1c7", bg1:   "#ebdbb2", bg2:   "#d5c4a1",
    bg3:   "#bdae93", bg4:   "#a89984",
    fg:    "#3c3836", fg1:   "#504945",
    red:   "#9d0006", redB:  "#cc241d",
    green: "#79740e", greenB:"#98971a",
    yellow:"#b57614", yellowB:"#d79921",
    blue:  "#076678", blueB: "#458588",
    purple:"#8f3f71", purpleB:"#b16286",
    aqua:  "#427b58", aquaB: "#689d6a",
    orange:"#af3a03", orangeB:"#d65d0e",
    gray:  "#7c6f64",
  },
}

;(function generateGruvbox() {
  const lines: string[] = ["/* Auto-generated by scripts/sync-themes.ts. Do not edit manually. */"]

  const dark = gruvbox.dark
  lines.push("", ...block(`html[data-site-theme="gruvbox-dark"]`, {
    background: dark.bg,       foreground: dark.fg,
    card: dark.bg1,            "card-foreground": dark.fg,
    popover: dark.bg1,         "popover-foreground": dark.fg,
    primary: dark.purpleB,     "primary-foreground": dark.bg,
    secondary: dark.bg3,       "secondary-foreground": dark.fg,
    muted: dark.bg1,           "muted-foreground": dark.fg1,
    accent: dark.bg3,          "accent-foreground": dark.fg,
    destructive: dark.redB,
    border: dark.bg4,          input: dark.bg1,
    ring: dark.aquaB,
    "chart-1": dark.greenB, "chart-2": dark.yellowB, "chart-3": dark.orangeB,
    "chart-4": dark.blueB,  "chart-5": dark.aquaB,
    sidebar: dark.bg1,              "sidebar-foreground": dark.fg,
    "sidebar-primary": dark.purpleB,"sidebar-primary-foreground": dark.bg,
    "sidebar-accent": dark.bg2,     "sidebar-accent-foreground": dark.fg,
    "sidebar-border": dark.bg3,     "sidebar-ring": dark.purpleB,
    link: dark.blueB,
    "hero-gradient-start": dark.bg,  "hero-gradient-end": dark.bg1,
    "badge-primary": dark.purpleB,   "tag-hover": dark.aquaB,
    "accent-1": dark.purpleB, "accent-2": dark.blueB, "accent-3": dark.greenB,
    "surface-raised": dark.bg1, "card-border-accent": dark.aquaB,
    highlight: dark.aquaB,
  }))

  const light = gruvbox.light
  lines.push("", ...block(`html[data-site-theme="gruvbox-light"]`, {
    background: light.bg,       foreground: light.fg,
    card: light.bg1,            "card-foreground": light.fg,
    popover: light.bg1,         "popover-foreground": light.fg,
    primary: light.purple,      "primary-foreground": light.bg,
    secondary: light.bg3,       "secondary-foreground": light.fg,
    muted: light.bg1,           "muted-foreground": light.fg1,
    accent: light.bg3,          "accent-foreground": light.fg,
    destructive: light.red,
    border: light.bg4,          input: light.bg1,
    ring: light.aqua,
    "chart-1": light.green,  "chart-2": light.yellow, "chart-3": light.orange,
    "chart-4": light.blue,   "chart-5": light.aqua,
    sidebar: light.bg1,              "sidebar-foreground": light.fg,
    "sidebar-primary": light.purple, "sidebar-primary-foreground": light.bg,
    "sidebar-accent": light.bg2,     "sidebar-accent-foreground": light.fg,
    "sidebar-border": light.bg3,     "sidebar-ring": light.purple,
    link: light.blue,
    "hero-gradient-start": light.bg,  "hero-gradient-end": light.bg1,
    "badge-primary": light.purple,    "tag-hover": light.aqua,
    "accent-1": light.purple, "accent-2": light.blue, "accent-3": light.green,
    "surface-raised": light.bg1, "card-border-accent": light.aqua,
    highlight: light.greenB,
  }))

  write("gruvbox.css", lines)
})()

// ---------------------------------------------------------------------------
// 3. Rosé Pine  (main / moon / dawn)
// ---------------------------------------------------------------------------
const rosePine = {
  main: {
    base:        "#191724", surface:     "#1f1d2e", overlay:     "#26233a",
    muted:       "#6e6a86", subtle:      "#908caa", text:        "#e0def4",
    love:        "#eb6f92", gold:        "#f6c177", rose:        "#ebbcba",
    pine:        "#31748f", foam:        "#9ccfd8", iris:        "#c4a7e7",
    highlightLow:"#21202e", highlightMed:"#403d52", highlightHigh:"#524f67",
  },
  moon: {
    base:        "#232136", surface:     "#2a273f", overlay:     "#393552",
    muted:       "#6e6a86", subtle:      "#908caa", text:        "#e0def4",
    love:        "#eb6f92", gold:        "#f6c177", rose:        "#ea9a97",
    pine:        "#3e8fb0", foam:        "#9ccfd8", iris:        "#c4a7e7",
    highlightLow:"#2a283e", highlightMed:"#44415a", highlightHigh:"#56526e",
  },
  dawn: {
    base:        "#faf4ed", surface:     "#fffaf3", overlay:     "#f2e9e1",
    muted:       "#9893a5", subtle:      "#797593", text:        "#575279",
    love:        "#b4637a", gold:        "#ea9d34", rose:        "#d7827a",
    pine:        "#286983", foam:        "#56949f", iris:        "#907aa9",
    highlightLow:"#f4ede8", highlightMed:"#dfdad9", highlightHigh:"#cecacd",
  },
}

;(function generateRosePine() {
  const lines: string[] = ["/* Auto-generated by scripts/sync-themes.ts. Do not edit manually. */"]

  for (const [variant, p] of Object.entries(rosePine) as [string, typeof rosePine.main][]) {
    const isDark = variant !== "dawn"
    const selector = `html[data-site-theme="rosepine-${variant}"]`
    lines.push("", ...block(selector, {
      background: p.base,        foreground: p.text,
      card: p.surface,           "card-foreground": p.text,
      popover: p.surface,        "popover-foreground": p.text,
      primary: p.rose,           "primary-foreground": p.base,
      secondary: p.highlightHigh, "secondary-foreground": p.text,
      muted: isDark ? p.highlightLow : p.overlay,
      "muted-foreground": p.subtle,
      accent: p.highlightHigh,   "accent-foreground": p.text,
      destructive: p.love,
      border: p.highlightMed,    input: p.surface,
      ring: p.iris,
      "chart-1": p.gold, "chart-2": p.rose, "chart-3": p.pine,
      "chart-4": p.foam, "chart-5": p.iris,
      sidebar: isDark ? p.highlightLow : p.overlay,
      "sidebar-foreground": p.text,
      "sidebar-primary": p.rose, "sidebar-primary-foreground": p.base,
      "sidebar-accent": p.overlay,"sidebar-accent-foreground": p.text,
      "sidebar-border": p.highlightMed, "sidebar-ring": p.rose,
      link: p.foam,
      "hero-gradient-start": p.base,   "hero-gradient-end": p.surface,
      "badge-primary": p.rose,         "tag-hover": p.iris,
      "accent-1": p.rose, "accent-2": p.foam, "accent-3": p.gold,
      "surface-raised": p.surface, "card-border-accent": p.iris,
      highlight: p.love,
    }))
  }

  write("rosepine.css", lines)
})()

// ---------------------------------------------------------------------------
// 4. Nord  (dark / light)
// ---------------------------------------------------------------------------
const nord = {
  n0:  "#2e3440", n1:  "#3b4252", n2:  "#434c5e", n3:  "#4c566a",
  n4:  "#d8dee9", n5:  "#e5e9f0", n6:  "#eceff4",
  n7:  "#8fbcbb", n8:  "#88c0d0", n9:  "#81a1c1", n10: "#5e81ac",
  n11: "#bf616a", n12: "#d08770", n13: "#ebcb8b", n14: "#a3be8c", n15: "#b48ead",
}

;(function generateNord() {
  const lines: string[] = ["/* Auto-generated by scripts/sync-themes.ts. Do not edit manually. */"]

  lines.push("", ...block(`html[data-site-theme="nord-dark"]`, {
    background: nord.n0,  foreground: nord.n6,
    card: nord.n1,        "card-foreground": nord.n6,
    popover: nord.n1,     "popover-foreground": nord.n6,
    primary: nord.n9,     "primary-foreground": nord.n0,
    secondary: nord.n3,   "secondary-foreground": nord.n6,
    muted: nord.n1,       "muted-foreground": nord.n5,
    accent: nord.n3,      "accent-foreground": nord.n6,
    destructive: nord.n11,
    border: nord.n3,      input: nord.n1,
    ring: nord.n15,
    "chart-1": nord.n11, "chart-2": nord.n12, "chart-3": nord.n13,
    "chart-4": nord.n14, "chart-5": nord.n15,
    sidebar: nord.n1,             "sidebar-foreground": nord.n6,
    "sidebar-primary": nord.n9,   "sidebar-primary-foreground": nord.n0,
    "sidebar-accent": nord.n2,    "sidebar-accent-foreground": nord.n6,
    "sidebar-border": nord.n3,    "sidebar-ring": nord.n9,
    link: nord.n8,
    "hero-gradient-start": nord.n0, "hero-gradient-end": nord.n1,
    "badge-primary": nord.n9,       "tag-hover": nord.n8,
    "accent-1": nord.n9, "accent-2": nord.n8, "accent-3": nord.n14,
    "surface-raised": nord.n1, "card-border-accent": nord.n15,
    highlight: nord.n8,
  }))

  lines.push("", ...block(`html[data-site-theme="nord-light"]`, {
    background: nord.n6,  foreground: nord.n0,
    card: nord.n5,        "card-foreground": nord.n0,
    popover: nord.n5,     "popover-foreground": nord.n0,
    primary: nord.n10,    "primary-foreground": nord.n6,
    secondary: nord.n3,   "secondary-foreground": nord.n6,
    muted: nord.n5,       "muted-foreground": nord.n2,
    accent: nord.n3,      "accent-foreground": nord.n6,
    destructive: nord.n11,
    border: nord.n3,      input: nord.n5,
    ring: nord.n15,
    "chart-1": nord.n11, "chart-2": nord.n12, "chart-3": nord.n13,
    "chart-4": nord.n14, "chart-5": nord.n15,
    sidebar: nord.n5,             "sidebar-foreground": nord.n0,
    "sidebar-primary": nord.n10,  "sidebar-primary-foreground": nord.n6,
    "sidebar-accent": nord.n4,    "sidebar-accent-foreground": nord.n0,
    "sidebar-border": nord.n4,    "sidebar-ring": nord.n10,
    link: nord.n10,
    "hero-gradient-start": nord.n6, "hero-gradient-end": nord.n5,
    "badge-primary": nord.n10,      "tag-hover": nord.n9,
    "accent-1": nord.n10, "accent-2": nord.n8, "accent-3": nord.n14,
    "surface-raised": nord.n5, "card-border-accent": nord.n15,
    highlight: nord.n8,
  }))

  write("nord.css", lines)
})()

// ---------------------------------------------------------------------------
// 5. Dracula
// ---------------------------------------------------------------------------
const drac = {
  bg:         "#282a36", currentLine:"#44475a", selection:  "#44475a",
  fg:         "#f8f8f2", comment:    "#6272a4",
  cyan:       "#8be9fd", green:      "#50fa7b", orange:     "#ffb86c",
  pink:       "#ff79c6", purple:     "#bd93f9", red:        "#ff5555",
  yellow:     "#f1fa8c",
}

;(function generateDracula() {
  const lines: string[] = ["/* Auto-generated by scripts/sync-themes.ts. Do not edit manually. */"]

  lines.push("", ...block(`html[data-site-theme="dracula"]`, {
    background: drac.bg,          foreground: drac.fg,
    card: drac.currentLine,       "card-foreground": drac.fg,
    popover: drac.currentLine,    "popover-foreground": drac.fg,
    primary: drac.purple,         "primary-foreground": drac.bg,
    secondary: drac.selection,    "secondary-foreground": drac.fg,
    muted: drac.bg,               "muted-foreground": drac.cyan,
    accent: drac.selection,       "accent-foreground": drac.fg,
    destructive: drac.red,
    border: drac.currentLine,     input: drac.currentLine,
    ring: drac.pink,
    "chart-1": drac.green, "chart-2": drac.yellow, "chart-3": drac.orange,
    "chart-4": drac.purple,"chart-5": drac.cyan,
    sidebar: drac.currentLine,          "sidebar-foreground": drac.fg,
    "sidebar-primary": drac.purple,     "sidebar-primary-foreground": drac.bg,
    "sidebar-accent": drac.selection,   "sidebar-accent-foreground": drac.fg,
    "sidebar-border": drac.selection,   "sidebar-ring": drac.purple,
    link: drac.cyan,
    "hero-gradient-start": drac.bg,    "hero-gradient-end": drac.currentLine,
    "badge-primary": drac.purple,      "tag-hover": drac.pink,
    "accent-1": drac.purple, "accent-2": drac.cyan, "accent-3": drac.green,
    "surface-raised": drac.currentLine, "card-border-accent": drac.pink,
    highlight: drac.pink,
  }))

  write("dracula.css", lines)
})()

// ---------------------------------------------------------------------------
// 6. Tokyo Night  (night / storm / day / moon)
// ---------------------------------------------------------------------------
const tokyoNight = {
  night: {
    bg:          "#1a1b26", bgDark:     "#16161e", bgHighlight:"#292e42",
    bgPopup:     "#1f2335", bgSearch:   "#3d59a1",
    fg:          "#c0caf5", fgDark:     "#a9b1d6",
    red:         "#f7768e", orange:     "#ff9e64", yellow:     "#e0af68",
    green:       "#9ece6a", teal:       "#73daca", cyan:       "#7dcfff",
    blue:        "#7aa2f7", magenta:    "#bb9af7", magentaLight:"#9d7cd8",
    border:      "#27283a", comment:    "#565f89",
  },
  storm: {
    bg:          "#24283b", bgDark:     "#1f2335", bgHighlight:"#292e42",
    bgPopup:     "#1f2335", bgSearch:   "#3d59a1",
    fg:          "#c0caf5", fgDark:     "#a9b1d6",
    red:         "#f7768e", orange:     "#ff9e64", yellow:     "#e0af68",
    green:       "#9ece6a", teal:       "#73daca", cyan:       "#7dcfff",
    blue:        "#7aa2f7", magenta:    "#bb9af7", magentaLight:"#9d7cd8",
    border:      "#29304d", comment:    "#565f89",
  },
  moon: {
    bg:          "#222436", bgDark:     "#1e2030", bgHighlight:"#2f334d",
    bgPopup:     "#1e2030", bgSearch:   "#3d59a1",
    fg:          "#c8d3f5", fgDark:     "#a9b8e8",
    red:         "#ff757f", orange:     "#ff966c", yellow:     "#ffc777",
    green:       "#c3e88d", teal:       "#4fd6be", cyan:       "#86e1fc",
    blue:        "#82aaff", magenta:    "#c099ff", magentaLight:"#fca7ea",
    border:      "#2f334d", comment:    "#636da6",
  },
}

;(function generateTokyoNight() {
  const lines: string[] = ["/* Auto-generated by scripts/sync-themes.ts. Do not edit manually. */"]

  for (const [variant, p] of Object.entries(tokyoNight) as [string, typeof tokyoNight.night][]) {
    const selector = `html[data-site-theme="tokyonight-${variant}"]`
    lines.push("", ...block(selector, {
      background: p.bg,          foreground: p.fg,
      card: p.bgHighlight,       "card-foreground": p.fg,
      popover: p.bgPopup,        "popover-foreground": p.fg,
      primary: p.magenta,        "primary-foreground": p.bg,
      secondary: p.bgHighlight,  "secondary-foreground": p.fg,
      muted: p.bgDark,
      "muted-foreground": p.fgDark,
      accent: p.bgHighlight,     "accent-foreground": p.fg,
      destructive: p.red,
      border: p.border,          input: p.bgHighlight,
      ring: p.blue,
      "chart-1": p.green, "chart-2": p.yellow, "chart-3": p.orange,
      "chart-4": p.blue,  "chart-5": p.magenta,
      sidebar: p.bgDark,
      "sidebar-foreground": p.fg,
      "sidebar-primary": p.magenta,  "sidebar-primary-foreground": p.bg,
      "sidebar-accent": p.bgHighlight, "sidebar-accent-foreground": p.fg,
      "sidebar-border": p.border,    "sidebar-ring": p.magenta,
      link: p.cyan,
      "hero-gradient-start": p.bg,  "hero-gradient-end": p.bgDark,
      "badge-primary": p.magenta,   "tag-hover": p.blue,
      "accent-1": p.magenta, "accent-2": p.blue, "accent-3": p.green,
      "surface-raised": p.bgHighlight, "card-border-accent": p.teal,
      highlight: p.blue,
    }))
  }

  write("tokyo-night.css", lines)
})()
