name: Sync Profile to Main Repo
on:
  push:
    branches:
      - portfolio-abhishek

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template repository
        uses: actions/checkout@v4
        with:
          ref: portfolio-abhishek
          fetch-depth: 0 # Fetches all history so git history remains intact

      - name: Push to Repo geekyguy1705.github.io
        run: |
          # Configure Git Identity
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Remove workflow files so they are not pushed
          rm -rf .github/workflows

          # Add geekyguy1705.github.io as a remote using the secret token
          # Replace 'your-username' with your actual GitHub username or Organization name
          git remote add target https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/geekyguy1705/geekyguy1705.github.io.git
          
          # Force push the current local branch (portfolio-abhishek) to geekyguy1705.github.io's main branch
          git push target geekyguy1705.github.io portfolio-abhishek:main --force